"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta


load_dotenv()


BASE_DIR = Path(__file__).resolve().parent.parent


SECRET_KEY = os.getenv("SECRET_KEY")

DEBUG = os.getenv(
    "DEBUG",
    "False"
).lower() == "true"


# ALLOWED_HOSTS = os.getenv(
#     "ALLOWED_HOSTS",
#     ""
# ).split(",")
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
]


INSTALLED_APPS = [

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",


    # Third party

    "rest_framework",
    "corsheaders",
    "drf_spectacular",


    # Local apps

    "accounts",
    "courses",
    "patterns",
    # "orders",
    # "payments",
    "commerce",
    "adminpanel",

]



MIDDLEWARE = [

    "corsheaders.middleware.CorsMiddleware",

    "django.middleware.security.SecurityMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",

    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",

]



ROOT_URLCONF = "config.urls"



TEMPLATES = [

    {

        "BACKEND": "django.template.backends.django.DjangoTemplates",

        "DIRS": [],

        "APP_DIRS": True,

        "OPTIONS": {

            "context_processors": [

                "django.template.context_processors.request",

                "django.contrib.auth.context_processors.auth",

                "django.contrib.messages.context_processors.messages",

            ],

        },

    },

]



WSGI_APPLICATION = "config.wsgi.application"



DATABASES = {

    "default": {

        "ENGINE": "django.db.backends.postgresql",

        "NAME": os.getenv("POSTGRES_DB"),

        "USER": os.getenv("POSTGRES_USER"),

        "PASSWORD": os.getenv("POSTGRES_PASSWORD"),

        "HOST": os.getenv("POSTGRES_HOST"),

        "PORT": os.getenv("POSTGRES_PORT"),

    }

}



AUTH_PASSWORD_VALIDATORS = [

    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },

    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },

    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },

    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },

]



LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True



STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"



MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"



DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



AUTH_USER_MODEL = "accounts.User"



CORS_ALLOW_CREDENTIALS = True


CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]



REST_FRAMEWORK = {

    "DEFAULT_SCHEMA_CLASS":
        "drf_spectacular.openapi.AutoSchema",


    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),


    "DEFAULT_PAGINATION_CLASS":
        "config.pagination.DefaultPagination",


    "PAGE_SIZE": 10,

}



SIMPLE_JWT = {


    "ACCESS_TOKEN_LIFETIME":

        timedelta(days=7),


    "REFRESH_TOKEN_LIFETIME":

        timedelta(days=30),

}



SPECTACULAR_SETTINGS = {
    "TITLE": "Tailoring Academy API",
    "DESCRIPTION": "Backend API",
    "VERSION": "1.0.0",

    "SERVE_INCLUDE_SCHEMA": True,

    "COMPONENT_SPLIT_REQUEST": True,

    "DISABLE_ERRORS_AND_WARNINGS": True,
}



ZARINPAL_MERCHANT_ID = "YOUR-MERCHANT-ID"


ZARINPAL_CALLBACK_URL = (

    "http://localhost:8000/api/payment/verify/"

)



CACHES = {


    "default": {


        "BACKEND":

            "django_redis.cache.RedisCache",


        "LOCATION":

            "redis://redis:6379/1",


        "OPTIONS": {


            "CLIENT_CLASS":

                "django_redis.client.DefaultClient",

        },

    }

}



CELERY_BROKER_URL = "redis://redis:6379/0"

CELERY_RESULT_BACKEND = "redis://redis:6379/1"


CELERY_ACCEPT_CONTENT = [

    "json"

]


CELERY_TASK_SERIALIZER = "json"

CELERY_RESULT_SERIALIZER = "json"

CELERY_TIMEZONE = "Asia/Tehran"