# Generated by Django 5.2.15 on 2026-07-08 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0002_patternpurchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatternPurchase',
        ),
    ]
